/**
 * T1.java
 * Created at 2020-9-25
 * Created by jun.zhao
 * Copyright (C) 2020 SHANGHAI VOLKSWAGEN, All rights reserved.
 */
package me.ooi.tinyquery.spring.test.po;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;
import me.ooi.tinyquery.annotation.Id;
import me.ooi.tinyquery.annotation.Table;

/**
* Created by Mybatis Generator on 2020-10-10 14:00:07
*/
@Data
@Table(name = "t1")
public class T1 implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.id
     *
     * @mbg.generated
     */
    /**
     * 
     */
    @Id(sequence = "t1_seq")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.name
     *
     * @mbg.generated
     */
    /**
     * 
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.user_sex
     *
     * @mbg.generated
     */
    /**
     * 
     */
    private Integer userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.user_birthday
     *
     * @mbg.generated
     */
    /**
     * 
     */
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.create_time
     *
     * @mbg.generated
     */
    /**
     * 
     */
    private Date createTime;
}